version: '3.9'

networks:
  grafana_loki:


services:
  loki:
    container_name: loki
    image: grafana/loki:2.6.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-data:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - grafana_loki

  promtail:
    container_name: promtail
    image: grafana/promtail:2.6.0
    volumes:
      - /var/log:/var/log
 #     - /home:/home:ro  # optional - add host mount path to container
      - ./promtail-data:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - grafana_loki

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana-data:/var/lib/grafana
      # - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#    user: '1000'
    networks:
      - grafana_loki

#    network_mode: "host" #optional when you want container to be on host
